export const COURSE_REQUEST = 'COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED';

export const COURSE_ADD = 'COURSE_ADD';
export const COURSE_ADD_FAILED = 'COURSE_ADD_FAILED';
export const COURSE_ADD_SUCCESS = 'COURSE_ADD_SUCCESS';