export const COURSE_REQUEST = 'COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED';

// export const COURSE_FILTER_REQUEST = 'COURSE_FILTER_REQUEST';
// export const COURSE_FILTER_SUCCESS = 'COURSE_FILTER_SUCCESS';
// export const COURSE_FILTER_FAILED = 'COURSE_FILTER_FAILED';

export const CART_COURSES_REQUEST = 'CART_COURSES_REQUEST';
export const CART_COURSES_SUCCESS = 'CART_COURSES_SUCCESS';
export const CART_COURSES_FAILED = 'CART_COURSES_FAILED';

export const COURSE_ADD = 'COURSE_ADD';
export const COURSE_ADD_FAILED = 'COURSE_ADD_FAILED';
export const COURSE_ADD_SUCCESS = 'COURSE_ADD_SUCCESS';

export const SECTION_REQUEST = 'SECTION_REQUEST';
export const GET_SECTION_SUCCESS = 'GET_SECTION_SUCCESS';
export const GET_SECTION_FAILED = 'GET_SECTION_FAILED';